add_newline = false

[aws]
disabled = true

[gcloud]
disabled = true

[hostname]
disabled = true

[cmd_duration]
disabled = true

[username]
disabled = true

[line_break]
disabled = true

[directory]
truncation_length = 1

[os]
format = "on [($name )]($style)"
disabled = false
style = "bold blue"
