format = """
[┌───────────────────>](bold green) $hostname$directory
[└─>](bold green) $all"""

add_newline = false

[aws]
disabled = true

[gcloud]
disabled = true

[hostname]
ssh_only = false

[cmd_duration]
disabled = true

[username]
disabled = true

[line_break]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 0

[os]
disabled = true
