format = """
[┌───────────────────>](bold green) $directory$os
[└─>](bold green) $all"""

add_newline = false

[aws]
disabled = true

[gcloud]
disabled = true

[hostname]
disabled = true

[cmd_duration]
disabled = true

[username]
disabled = true

[line_break]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 0

[os]
format = "on [($name )]($style)"
disabled = false
style = "bold blue"
