#! /bin/sh

# TODO: set up displays
xrandr --auto

# Start xinitrc scripts
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Setup keyring
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

exec awesome
